packages:
  - apps/*
  - packages/*
  - services/*
overrides:
  "esbuild@>=0.27.3 <0.28.1": 0.28.1
  shell-quote: 1.10.0
allowBuilds:
  electron: true
  electron-winstaller: false
  esbuild: true
  libxmljs2: set this to true or false
  workerd: true
