import { z } from "zod";
export { ipcChannels } from "./channels.js";

export const BrowserCommandSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("new-tab"), url: z.string().optional() }),
  z.object({ type: z.literal("new-private-window") }),
  z.object({ type: z.literal("create-profile"), name: z.string().trim().min(1).max(48) }),
  z.object({ type: z.literal("open-profile"), profileId: z.string().min(1) }),
  z.object({ type: z.literal("rename-profile"), profileId: z.string().min(1), name: z.string().trim().min(1).max(48) }),
  z.object({ type: z.literal("delete-profile"), profileId: z.string().min(1) }),
  z.object({ type: z.literal("select-tab"), tabId: z.string().min(1) }),
  z.object({ type: z.literal("close-tab"), tabId: z.string().min(1) }),
  z.object({ type: z.literal("reorder-tab"), tabId: z.string().min(1), beforeTabId: z.string().min(1) }),
  z.object({ type: z.literal("navigate"), value: z.string().min(1) }),
  z.object({ type: z.literal("back") }),
  z.object({ type: z.literal("forward") }),
  z.object({ type: z.literal("reload") }),
  z.object({ type: z.literal("stop") }),
  z.object({ type: z.literal("toggle-sidebar") }),
  z.object({ type: z.literal("set-sidebar-section"), section: z.enum(["tabs", "bookmarks", "history", "downloads", "spaces", "conversations", "settings"]) }),
  z.object({ type: z.literal("create-tab-group"), tabId: z.string().min(1).optional() }),
  z.object({ type: z.literal("rename-tab-group"), groupId: z.string().min(1), name: z.string().trim().min(1).max(48) }),
  z.object({ type: z.literal("toggle-tab-group"), groupId: z.string().min(1) }),
  z.object({ type: z.literal("set-tab-group"), tabId: z.string().min(1), groupId: z.string().min(1).nullable() }),
  z.object({ type: z.literal("delete-tab-group"), groupId: z.string().min(1) }),
  z.object({ type: z.literal("toggle-bookmark") }),
  z.object({ type: z.literal("remove-bookmark"), bookmarkId: z.string().min(1) }),
  z.object({ type: z.literal("open-library-item"), url: z.string().min(1) }),
  z.object({ type: z.literal("reveal-download"), downloadId: z.string().min(1) }),
  z.object({ type: z.literal("cancel-download"), downloadId: z.string().min(1) }),
  z.object({ type: z.literal("toggle-find") }),
  z.object({ type: z.literal("find-in-page"), query: z.string().max(10_000), forward: z.boolean().optional(), findNext: z.boolean().optional() }),
  z.object({ type: z.literal("close-find") }),
  z.object({ type: z.literal("zoom-in") }),
  z.object({ type: z.literal("zoom-out") }),
  z.object({ type: z.literal("zoom-reset") }),
  z.object({ type: z.literal("print-page") }),
  z.object({ type: z.literal("save-page-pdf") }),
  z.object({ type: z.literal("toggle-tab-mute"), tabId: z.string().min(1) }),
  z.object({ type: z.literal("toggle-media-playback") }),
  z.object({ type: z.literal("sleep-tab"), tabId: z.string().min(1) }),
  z.object({ type: z.literal("answer-site-permission"), requestId: z.string().min(1), decision: z.enum(["allow-once", "always", "deny"]) }),
  z.object({ type: z.literal("reset-site-permission"), origin: z.string().min(1), permission: z.string().min(1) }),
  z.object({ type: z.literal("set-appearance"), appearance: z.enum(["system", "light", "dark"]) }),
  z.object({ type: z.literal("set-search-engine"), searchEngine: z.enum(["duckduckgo", "brave", "google", "bing"]) }),
  z.object({ type: z.literal("set-sleep-after"), minutes: z.union([z.literal(0), z.literal(15), z.literal(30), z.literal(60)]) }),
  z.object({ type: z.literal("choose-download-directory") }),
  z.object({ type: z.literal("set-extension-developer-mode"), enabled: z.boolean() }),
  z.object({ type: z.literal("install-unpacked-extension") }),
  z.object({ type: z.literal("set-extension-enabled"), extensionId: z.string().min(1).max(255), enabled: z.boolean() }),
  z.object({ type: z.literal("remove-extension"), extensionId: z.string().min(1).max(255) }),
  z.object({
    type: z.literal("complete-onboarding"),
    searchEngine: z.enum(["duckduckgo", "brave", "google", "bing"]),
    appearance: z.enum(["system", "light", "dark"]),
    sleepAfterMinutes: z.union([z.literal(0), z.literal(15), z.literal(30), z.literal(60)]),
  }),
  z.object({ type: z.literal("autofill-credential"), credentialId: z.string().min(1) }),
  z.object({ type: z.literal("save-pending-credential") }),
  z.object({ type: z.literal("dismiss-pending-credential") }),
  z.object({ type: z.literal("delete-credential"), credentialId: z.string().min(1) }),
  z.object({ type: z.literal("begin-sync-registration"), displayName: z.string().trim().min(1).max(80), serviceUrl: z.string().url().max(2_048) }),
  z.object({ type: z.literal("begin-sync-sign-in"), recoveryKey: z.string().trim().min(40).max(256), serviceUrl: z.string().url().max(2_048) }),
  z.object({ type: z.literal("begin-sync-device-enrollment"), serviceUrl: z.string().url().max(2_048) }),
  z.object({ type: z.literal("check-sync-device-enrollment") }),
  z.object({ type: z.literal("cancel-sync-device-enrollment") }),
  z.object({ type: z.literal("copy-sync-pairing-code") }),
  z.object({ type: z.literal("approve-sync-device"), pairingCode: z.string().trim().min(40).max(256) }),
  z.object({ type: z.literal("revoke-sync-device"), deviceId: z.string().min(8).max(128) }),
  z.object({ type: z.literal("rotate-sync-recovery-key") }),
  z.object({ type: z.literal("sync-now") }),
  z.object({ type: z.literal("disconnect-sync") }),
  z.object({ type: z.literal("delete-sync-cloud-data") }),
  z.object({ type: z.literal("delete-sync-account") }),
  z.object({ type: z.literal("toggle-work") }),
  z.object({ type: z.literal("set-work-width"), width: z.number().finite() }),
  z.object({ type: z.literal("set-reduced-motion"), enabled: z.boolean() }),
  z.object({ type: z.literal("share-active-tab"), level: z.enum(["read", "interact"]) }),
  z.object({ type: z.literal("revoke-active-tab") }),
  z.object({ type: z.literal("set-work-mode"), mode: z.enum(["ask", "work", "plan", "build"]) }),
  z.object({
    type: z.literal("set-work-panel"),
    panel: z.enum(["chat", "plan", "changes", "files", "terminal"]),
  }),
  z.object({ type: z.literal("new-work-conversation") }),
  z.object({ type: z.literal("select-work-conversation"), sessionId: z.string().trim().min(1).max(255) }),
  z.object({ type: z.literal("choose-workspace") }),
  z.object({ type: z.literal("request-work-plan") }),
  z.object({ type: z.literal("approve-work-plan") }),
  z.object({ type: z.literal("revise-work-plan") }),
  z.object({ type: z.literal("refresh-work-changes") }),
  z.object({ type: z.literal("select-work-change"), path: z.string().trim().min(1).max(2_048), staged: z.boolean().optional() }),
  z.object({ type: z.literal("refresh-work-files") }),
  z.object({ type: z.literal("select-work-file"), path: z.string().trim().min(1).max(2_048) }),
  z.object({ type: z.literal("clear-work-terminal") }),
  z.object({ type: z.literal("restart-work-runtime") }),
  z.object({ type: z.literal("choose-work-attachments") }),
  z.object({ type: z.literal("remove-work-attachment"), attachmentId: z.string().uuid() }),
  z.object({
    type: z.literal("configure-work-provider"),
    providerId: z.enum(["openai-api", "kimi", "claude-api", "vllm"]),
    model: z.string().trim().min(1).max(1_024),
    baseUrl: z.string().trim().max(2_048).optional(),
  }),
  z.object({
    type: z.literal("select-work-model"),
    providerId: z.enum(["chatgpt-plan", "openai-api", "kimi", "claude-api", "vllm", "local"]),
    model: z.string().trim().min(1).max(1_024),
  }),
  z.object({ type: z.literal("start-chatgpt-login") }),
  z.object({ type: z.literal("sign-out-chatgpt") }),
  z.object({ type: z.literal("refresh-work-models") }),
  z.object({ type: z.literal("work-send"), text: z.string().trim().min(1).max(200_000) }),
  z.object({ type: z.literal("stop-work") }),
  z.object({ type: z.literal("answer-permission"), requestId: z.string().min(1), decision: z.enum(["allow", "always", "deny"]) }),
]);

export type BrowserCommand = z.infer<typeof BrowserCommandSchema>;
