import { z } from "zod";
export { ipcChannels } from "./channels.js";

export const BrowserCommandSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("new-tab"), url: z.string().optional() }),
  z.object({ type: z.literal("new-private-window") }),
  z.object({ type: z.literal("create-profile"), name: z.string().trim().min(1).max(48) }),
  z.object({ type: z.literal("open-profile"), profileId: z.string().min(1) }),
  z.object({ type: z.literal("rename-profile"), profileId: z.string().min(1), name: z.string().trim().min(1).max(48) }),
  z.object({ type: z.literal("delete-profile"), profileId: z.string().min(1) }),
  z.object({ type: z.literal("select-tab"), tabId: z.string().min(1) }),
  z.object({ type: z.literal("close-tab"), tabId: z.string().min(1) }),
  z.object({ type: z.literal("reorder-tab"), tabId: z.string().min(1), beforeTabId: z.string().min(1) }),
  z.object({ type: z.literal("navigate"), value: z.string().min(1) }),
  z.object({ type: z.literal("back") }),
  z.object({ type: z.literal("forward") }),
  z.object({ type: z.literal("reload") }),
  z.object({ type: z.literal("stop") }),
  z.object({ type: z.literal("toggle-sidebar") }),
  z.object({ type: z.literal("set-sidebar-section"), section: z.enum(["tabs", "bookmarks", "history", "downloads", "spaces", "conversations", "settings"]) }),
  z.object({ type: z.literal("create-tab-group"), tabId: z.string().min(1).optional() }),
  z.object({ type: z.literal("rename-tab-group"), groupId: z.string().min(1), name: z.string().trim().min(1).max(48) }),
  z.object({ type: z.literal("toggle-tab-group"), groupId: z.string().min(1) }),
  z.object({ type: z.literal("set-tab-group"), tabId: z.string().min(1), groupId: z.string().min(1).nullable() }),
  z.object({ type: z.literal("delete-tab-group"), groupId: z.string().min(1) }),
  z.object({ type: z.literal("toggle-bookmark") }),
  z.object({ type: z.literal("remove-bookmark"), bookmarkId: z.string().min(1) }),
  z.object({ type: z.literal("open-library-item"), url: z.string().min(1) }),
  z.object({ type: z.literal("reveal-download"), downloadId: z.string().min(1) }),
  z.object({ type: z.literal("cancel-download"), downloadId: z.string().min(1) }),
  z.object({ type: z.literal("toggle-find") }),
  z.object({ type: z.literal("find-in-page"), query: z.string().max(10_000), forward: z.boolean().optional(), findNext: z.boolean().optional() }),
  z.object({ type: z.literal("close-find") }),
  z.object({ type: z.literal("zoom-in") }),
  z.object({ type: z.literal("zoom-out") }),
  z.object({ type: z.literal("zoom-reset") }),
  z.object({ type: z.literal("print-page") }),
  z.object({ type: z.literal("save-page-pdf") }),
  z.object({ type: z.literal("toggle-tab-mute"), tabId: z.string().min(1) }),
  z.object({ type: z.literal("toggle-media-playback") }),
  z.object({ type: z.literal("sleep-tab"), tabId: z.string().min(1) }),
  z.object({ type: z.literal("answer-site-permission"), requestId: z.string().min(1), decision: z.enum(["allow-once", "always", "deny"]) }),
  z.object({ type: z.literal("reset-site-permission"), origin: z.string().min(1), permission: z.string().min(1) }),
  z.object({ type: z.literal("set-appearance"), appearance: z.enum(["system", "light", "dark"]) }),
  z.object({ type: z.literal("set-search-engine"), searchEngine: z.enum(["duckduckgo", "brave", "google", "bing"]) }),
  z.object({ type: z.literal("set-sleep-after"), minutes: z.union([z.literal(0), z.literal(15), z.literal(30), z.literal(60)]) }),
  z.object({ type: z.literal("choose-download-directory") }),
  z.object({ type: z.literal("toggle-work") }),
  z.object({ type: z.literal("set-work-width"), width: z.number().finite() }),
  z.object({ type: z.literal("set-reduced-motion"), enabled: z.boolean() }),
  z.object({ type: z.literal("share-active-tab"), level: z.enum(["read", "interact"]) }),
  z.object({ type: z.literal("revoke-active-tab") }),
  z.object({ type: z.literal("set-work-mode"), mode: z.enum(["ask", "work", "plan", "build"]) }),
  z.object({
    type: z.literal("set-work-panel"),
    panel: z.enum(["chat", "overview", "plan", "changes", "files", "terminal", "checkpoints", "runs", "notes", "agents"]),
  }),
  z.object({ type: z.literal("work-send"), text: z.string().trim().min(1).max(200_000) }),
  z.object({ type: z.literal("stop-work") }),
  z.object({ type: z.literal("answer-permission"), requestId: z.string().min(1), decision: z.enum(["allow", "always", "deny"]) }),
]);

export type BrowserCommand = z.infer<typeof BrowserCommandSchema>;
