import type { BrowserCommand } from "../shared/ipc.js";

const SHELL_ONLY_COMMANDS = new Set<BrowserCommand["type"]>([
  "open-settings",
  "close-settings",
  "set-accent-color",
  "set-local-models-enabled",
  "set-semantic-recall-enabled",
  "clear-semantic-recall",
  "delete-recall-document",
  "add-recall-exclusion",
  "remove-recall-exclusion",
  "connect-walrus-memory",
  "disconnect-walrus-memory",
  "manage-walrus-delegates",
  "begin-walrus-page-memory",
  "begin-walrus-research-memory",
  "cancel-walrus-memory-draft",
  "save-walrus-memory-draft",
  "restore-walrus-memory",
  "configure-walrus-client-encrypted",
  "set-walrus-memory-mode",
  "generate-research-board",
  "export-research-board",
  "prepare-walrus-research-bundle",
  "publish-walrus-research-bundle",
  "cancel-walrus-research-bundle",
  "delete-research-board",
  "apply-tab-steward",
  "save-resume-bundle",
  "delete-resume-bundle",
  "execute-palette-action",
  "complete-onboarding",
  "autofill-credential",
  "save-pending-credential",
  "dismiss-pending-credential",
  "delete-credential",
  "set-extension-developer-mode",
  "install-unpacked-extension",
  "install-signed-extension",
  "refresh-extension-gallery",
  "install-gallery-extension",
  "set-extension-enabled",
  "rollback-extension",
  "remove-extension",
  "begin-sync-registration",
  "begin-sync-sign-in",
  "begin-sync-device-enrollment",
  "check-sync-device-enrollment",
  "cancel-sync-device-enrollment",
  "copy-sync-pairing-code",
  "approve-sync-device",
  "revoke-sync-device",
  "rotate-sync-recovery-key",
  "sync-now",
  "disconnect-sync",
  "delete-sync-cloud-data",
  "delete-sync-account",
  "configure-speech",
  "download-speech-model",
  "test-work-provider-credential",
  "remove-work-provider-credential",
  "start-recording",
  "pause-recording",
  "resume-recording",
  "stop-recording",
  "set-recording-source",
  "delete-recording-transcript",
  "reveal-recording-video",
]);

const WORK_ONLY_COMMANDS = new Set<BrowserCommand["type"]>([
  "open-walrus-memory-source",
  "attach-walrus-memory",
  "remove-walrus-memory-attachment",
]);

export function requiresShellSender(command: BrowserCommand): boolean {
  return SHELL_ONLY_COMMANDS.has(command.type);
}

export function requiresWorkSender(command: BrowserCommand): boolean {
  return WORK_ONLY_COMMANDS.has(command.type);
}
